work_dir: work_dir/SkeAttnCLR_/xsub/motion/semi0.1
weights:  work_dir/SkeAttnCLR_/xsub/motion/pretext/epoch300_model.pt
# weights:  work_dir/SkeMixLWL/pretext/best_8heads.pt
ignore_weights: [encoder_q.backbone.fc, encoder_q.neck, encoder_k, predictor, predictor_p, predictor_c, queue_z, queue_p, queue_c, queue_ptr_z, queue_ptr_p, queue_ptr_c]
# ignore_weights: [encoder_q.backbone.fc, encoder_q.neck, encoder_k, predictor, predictor_p, predictor_c, queue_z, queue_p, queue_c, queue_ptr_z, queue_ptr_p, queue_ptr_c]

# feeder
train_feeder: feeder.ntu_feeder.Feeder_semi
train_feeder_args:
  data_path: data/NTU60_frame64/xsub/train_position.npy
  label_path: data/NTU60/xsub/train_label.pkl
  label_percent: 0.1
  shear_amplitude: -1
  temperal_padding_ratio: -1
  window_size: 64
  center: True
  mmap: True
  
test_feeder: feeder.ntu_feeder.Feeder_single
test_feeder_args:
  data_path: data/NTU60_frame64/xsub/val_position.npy
  label_path: data/NTU60/xsub/val_label.pkl 
  shear_amplitude: -1
  temperal_padding_ratio: -1
  window_size: 64
  center: True
  mmap: True

# model
model: net.SkeAttnCLR.SkeAttnMask
model_args:
  base_encoder: net.st_gcn.Model
  pretrain: False
#  feature_dim: 128
#  queue_size: 32768
#  momentum: 0.996
#  Temperature: 0.07
  in_channels: 3
  hidden_channels: 64
  hidden_dim: 256
  num_class: 60
  dropout: 0.5
  # attn_drop: 0.
  # proj_drop: 0.
  # drop_path: 0.1
  loss_weight: 0.5
  heads: 8
#  norm_layer: None
#  num_mlp: 2
  # scale: 1.
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'
  edge_importance_weighting: True

# optim
nesterov: False
weight_decay: 0.0
base_lr: 0.003
optimizer: SGD
# step: [80, 150, 220]
step: [60, 100]

# training
device: [2]
batch_size: 128
test_batch_size: 128
num_epoch: 150
view: 'motion'

# log
save_result: True
save_interval: -1
eval_interval: 5
knn_interval: -1
