work_dir: work_dir/SkeAttnCLR_/xview/joint/Tsne
weights:  work_dir/SkeAttnCLR_/xview/joint/pretext/epoch300_model.pt
# weights:  work_dir/SkeMixLWL/pretext/best_8heads.pt
ignore_weights: [encoder_k, predictor_p, predictor_c, queue_z, queue_p, queue_c, queue_ptr_z, queue_ptr_p, queue_ptr_c]
# feeder
train_feeder: feeder.ntu_feeder.Feeder_single
train_feeder_args:
  data_path: data/NTU60_frame64/xview/train_position.npy
  label_path: data/NTU60/xview/train_label.pkl
  shear_amplitude: -1
  temperal_padding_ratio: -1
  window_size: 64
  center: True
  mmap: True
  
test_feeder: feeder.ntu_feeder.Feeder_single
test_feeder_args:
  data_path: data/NTU60_frame64/xview/val_position.npy
  label_path: data/NTU60/xview/val_label.pkl 
  shear_amplitude: -1
  temperal_padding_ratio: -1
  window_size: 64
  center: True
  mmap: True
# memory feeder for knn
mem_train_feeder: feeder.ntu_feeder.Feeder_semi
mem_train_feeder_args:
  data_path: data/NTU60_frame64/xview/train_position.npy
  label_path: data/NTU60/xview/train_label.pkl
  label_percent: 0.2 
  shear_amplitude: 0.5
  temperal_padding_ratio: 6
  window_size: 64
  center: True
  mmap: True
mem_test_feeder: feeder.ntu_feeder.Feeder_single
mem_test_feeder_args:
  data_path: data/NTU60_frame64/xview/val_position.npy
  label_path: data/NTU60/xview/val_label.pkl 
  shear_amplitude: 0.5
  temperal_padding_ratio: 6
  window_size: 64
  center: True
  mmap: True
# model
model: net.SkeAttnCLR.SkeAttnMask
model_args:
  base_encoder: net.st_gcn.Model
  pretrain: True
  feature_dim: 128
  queue_size: 32768
  momentum: 0.996
  Temperature: 0.2
  in_channels: 3
  hidden_channels: 64
  hidden_dim: 256
  num_class: 60
  dropout: 0.5
  Lambda: 2
  # attn_drop: 0.
  # proj_drop: 0.
  # drop_path: 0.1
  spa_l: 3
  spa_u: 4
  tem_l: 4
  tem_u: 7
  loss_weight: 0.5
  heads: 8
#  norm_layer: None
  # num_mlp: 2
  # scale: 1.
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'
  edge_importance_weighting: True

# optim
nesterov: False
weight_decay: 0.0
base_lr: 0.005
optimizer: SGD
# step: [80, 150, 220]
step: [60, 100]

# training
device: [1]
batch_size: 128
test_batch_size: 128
num_epoch: 1
view: 'joint'

# log
# save_result: True
save_interval: -1
eval_interval: -1
knn_interval: 1
# knn_k: [10, 20, 40]
# knn_classes: 60
# knn_t: 0.1
# KNN_show: [50, 100, 150, 200, 250, 300]
